name: Updating the StoryBook Docs frontend
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build, lint, test on ubuntu-latest and deploy

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: yarn install

            - name: Install Github Pages
              run: yarn add -D gh-pages

            - run: git config --global user.name "GitHub CD bot"
            - run: git config --global user.email "dmitrii@moralis.io"
            - run: git config --global user.signingkey ${{ secrets.GITHUB_TOKEN }}

            - name: Test
              run: yarn test --ci --coverage --maxWorkers=2 --updateSnapshot

            - name: Build Storybook
              run: yarn build-storybook

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook-static
